version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - frontend


  frontend:
    build: ./frontend/todo-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/todo-app:/app

